name: Take Screenshot of main page on push

on: [push]

jobs:


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "screenshot-pipeline"
          heroku_email: "vinicius.bass@outlook.com"

  take-screenshot:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "17.x"

      - name: Install dependencies
        run: npm install

      - name: Take screenshot
        run: npm run take-index-screenshot