name: Take Screenshot of main page on push

on: [push]

jobs:


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "screenshot-pipeline"
          heroku_email: "vinicius.bass@outlook.com"

  take-screenshot:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_TOKEN }}
          persist-credentials: true
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "17.x"

      - name: Install dependencies
        run: npm install

      - name: Take screenshot
        run: npm run take-index-screenshot

      - name: Set Credentials
        run: |
          git config --global user.email "Vinny-Bass"
          git config --global user.name "raylee558@gmail.com"

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: git commit -m "Auto updating Readme Image"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}